-- Create the crowd_density table with expanded schema
CREATE TABLE IF NOT EXISTS crowd_density (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_name TEXT NOT NULL,
  coordinates JSONB NOT NULL,
  density_level TEXT NOT NULL CHECK (density_level IN ('low', 'medium', 'high', 'critical')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  crowd_size INTEGER,
  occupancy_percentage TEXT,
  meta_data JSONB
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_crowd_density_updated_at ON crowd_density(updated_at);

-- Set up Row Level Security (RLS)
ALTER TABLE crowd_density ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read data
CREATE POLICY "Allow public read access" ON crowd_density
  FOR SELECT USING (true);

-- Create policy to allow service role to insert/update/delete
CREATE POLICY "Allow service role to manage data" ON crowd_density
  FOR ALL USING (auth.role() = 'service_role');

-- Add function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add trigger to update timestamp on update
CREATE TRIGGER update_crowd_density_timestamp
BEFORE UPDATE ON crowd_density
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- Add initial sample data (in case your automated system doesn't run immediately)
INSERT INTO crowd_density (location_name, coordinates, density_level, updated_at)
VALUES
  ('Masjid al-Haram', '{"lng": 39.826174, "lat": 21.422487}', 'high', NOW()),
  ('Mina', '{"lng": 39.892966, "lat": 21.413249}', 'medium', NOW()),
  ('Jamaraat Bridge', '{"lng": 39.873485, "lat": 21.42365}', 'critical', NOW()),
  ('Arafat', '{"lng": 39.984687, "lat": 21.355461}', 'low', NOW()),
  ('Muzdalifah', '{"lng": 39.936322, "lat": 21.383082}', 'medium', NOW()),
  ('Mina Entrance Gate 1', '{"lng": 39.887235, "lat": 21.411856}', 'high', NOW()),
  ('Tent City Section A', '{"lng": 39.889124, "lat": 21.414501}', 'medium', NOW()),
  ('Jamarat Central Access', '{"lng": 39.871952, "lat": 21.423850}', 'critical', NOW());

-- Instructions for .env.local file:
-- Create a .env.local file in your project root with the following:
-- 
-- ```
-- NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
-- NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
-- SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key
-- ```
--
-- Replace each value with the actual keys from your Supabase project. 